//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion
    {
        public int promoID { get; set; }
        public string promoImg { get; set; }
        public string promoImg2 { get; set; }
        public string promoImg3 { get; set; }
        public string promoDescript { get; set; }
        public decimal oriPrice { get; set; }
        public decimal disPrice { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public int prodID { get; set; }
        public string promoColor { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
